tests: Fix unit test to not rely on undefined globals
The other tests in this repo (that call source code, which calls WikiMap)
use MockWikiMapTrait. PageChangeEventIngressTest is a pure unit test
which disables the service container and so can't use that.

Instead, it mocked wgConf, which is fine, but it failed to *also*
set the regular globals. This made the test unrealistic because it is
impossible to call WikiMap at runtime in a situation where $wgServer
is null or unset, because it is always set in Setup.php.

The reason it mocked wgConf is because there is a bug in WikiMap that
doesn't recognise the current wiki in most cases. I'm fixing this
bug in I46dd9c35452.

Update this test to first set the normal globals and then (preserving
the workaround that was already here) also set wgConf. In the future
this workaround can be removed.

Without this update, I46dd9c35452 fails PageChangeEventIngressTest:

```
1) MediaWiki\Extension\EventBus\Tests\Unit\PageChangeEventIngressTest::testPageRevisionUpdatedWithEdit
   TypeError: WikiReference::__construct():
   Argument #1 ($canonicalServer) must be of type string, null given,
   called in /includes/WikiMap/WikiMap.php on line 30
   /includes/WikiMap/WikiReference.php:27
   /includes/WikiMap/WikiMap.php:30
   /extensions/EventBus/includes/Serializers/EventSerializer.php:109
```

Bug: T428296
Change-Id: If87dca635cce12d3fa1d0af8fd712bdf4eaedc42